/*
 * This source file was generated by the Gradle 'init' task
 */

package com.github.petarov.mdm.shared;

import org.junit.jupiter.api.Test;

class LibraryTest {

	@Test
	void someLibraryMethodReturnsTrue() {
	}
}
